name: Java CI Pipeline

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master


jobs:

  build-test:

    runs-on: ubuntu-latest

    steps:


      - name: Checkout code
        uses: actions/checkout@v6



      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          java-version: '17'
          distribution: 'temurin'



      - name: Build and Test
        run: mvn clean verify



      - name: SpotBugs scan
        run: mvn spotbugs:check


      # 5. Docker build
      - name: Build Docker image
        run: docker build -t inventory-app .