apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inventory-chart.fullname" . }}-config
  labels:
    {{- include "inventory-chart.labels" . | nindent 4 }}

data:
  SPRING_DATASOURCE_URL: {{ .Values.database.url | quote }}