name: Java CI Pipeline

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: InventoryManagement
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d InventoryManagement"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Test
        working-directory: ./InventoryManagement
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/InventoryManagement
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: postgres
        run: mvn clean verify

      - name: SpotBugs scan
        working-directory: ./InventoryManagement
        run: mvn spotbugs:spotbugs

      - name: Build Docker image
        working-directory: ./InventoryManagement
        run: docker build -t inventory-app .
